### PR TITLE
Added async Send methods

### PR DESCRIPTION
**Pull request by AlistairClark7**
I've added async methods to the Send(Lookup l) and Send(Batch b) methods. .NET framework version hasn't been upgraded. Let me know if you'd like more detail/require any changes/signing on contribution agreements.

### CODE REVIEW

**Comment by mdwhatcott** [comment]
[C# SDK: Async PR](https://trello.com/c/7OaIbQPD/1621-c-sdk-async-pr)

**Comment by mdwhatcott** [comment]
@AlistairClark7 - Wow, you've been hard at work here! Because this pull request represents some rather invasive changes we have a few questions to ask. (For future reference, a pull request of this scope and size will have the best chance of being merged when it is the result of a detailed discussion with SmartyStreets developers in a [separate github "issue"](https://github.com/smartystreets/smartystreets-csharp-sdk/issues/new).)

Here are the questions:

1. What is the use case in your work that necessitated the addition of `async` methods?
2. Why the additional `app.config` files?
3. The using directives you provided were placed outside the namespace declarations (contrary to the existing using directives which live inside a namespace declaration). Why the change in style?
4. Did you consider implementing a [wrapper on top of the existing SDK behavior to achieve asynchronous execution](http://stackoverflow.com/a/36440553)? If so, would that approach meet your needs?

**Comment by AlistairClark7** [comment]
Thanks for getting back to me! I've not done many PRs, so wasn't sure how to approach things! Will open an issue in future. It's definitely quite invasive, so I'll try and answer the question as best I can.

1. During a web request I'm looking up the lat/long of two addresses, and also retrieving some information from the database. So I don't want two blocking, synchronous calls to the smarty streets API. The blocking calls to the API aren't going to realistically affect the response time massively, but if I can reduce it by sending the calls off together then that's preferable.
2. I am not sure about this. These were added by nuget when I installed the Microsoft.Bcl.Async package.
3. Sorry about these! I use [ReSharper](https://www.jetbrains.com/resharper/) which automatically adds in the using statements. So I didn't actually look to see where they ended up. I will update them to match the current style.
4. Wrapping a synchronous call in Task.Run is slightly different to using async/await with an asynchronous method. Wrapping a synchronous call (like the existing Send methods) in Task.Run means that the task is still executing blocking work, blocking a thread pool thread the whole time the operation is in progress. Using async/await the thread can be reused as soon as the web request is sent off. This means that you can handle many more concurrent requests using the async requests, rather than wrapping blocking work in Task.Run. See [this article](http://blog.stephencleary.com/2013/11/taskrun-etiquette-examples-using.html) for more detail.

**Comment by mdwhatcott** [comment]
Thanks for clarifying, that helps. Here's a rough overview of our plan for this SDK (and all our other SDK's we plan to build):

**Step 1** (_in progress_): implement a simple, blocking client for the [US Street API](https://smartystreets.com/docs/us-street-api) and the [US ZIP Code API](https://smartystreets.com/docs/us-zipcode-api) in several of the most popular languages:

- [Java/JVM](https://github.com/smartystreets/smartystreets-java-sdk) (_finished_)
- [C#/.Net](https://github.com/smartystreets/smartystreets-csharp-sdk) (_finished)
- [Go](https://github.com/smartystreets/smartystreets-go-sdk) (_finished_)
- Python (_almost finished_)
- Objective-C (_almost finished_)
- Node.js (_just started_)
- PHP
- Ruby
- Cobol (_just kidding_)
- etc...

**Step 2** (_future_): implement clients for the [US Autocomplete API](https://smartystreets.com/docs/us-autocomplete-api), [US Extract API](https://smartystreets.com/docs/us-extract-api), and [International Street API](https://smartystreets.com/docs/international-street-api) for each language above.

**Step 3** (_future_): Add features that will be helpful to each SDK according to that language's community...

So, the priority right now is to implement a minimum feature set across various languages and then add coverage for each API we offer for each of those languages. So, it may be some time before we come back to evaluate the merits of an asynchronous implementation for the C# SDK. Stay tuned...

**Comment by AlistairClark7** [comment]
Ok no problem, thanks for the heads up and the roadmap! I'll leave my fork up and just build from that for my usages.

For Step 2, I will probably be using these features (almost definitely the International Street API). So if I start implementing these features before you get round to doing them, what would be the best way for me to develop them with an eventual PR in mind?

**Comment by mdwhatcott** [comment]
Well, the plan is for the new clients to all look and feel the same and for the initial implementation of each client to be simple (and synchronous).

**Pull request closed without merging**
